project:
  type: website
  output-dir: docs
website:
  title: "ML_blogs"
  navbar:
    right:
      - about.qmd
      - icon: envelope
        href: warisk@vt.edu
      - icon: twitter
        href: https://twitter.com/war_is11
      - icon: linkedin
        href: www.linkedin.com/in/waris-khan-s

format:
  html:
    theme: cosmo
    css: styles.css



