project:
  type: website
  output-dir: docs
website:
  title: "Learning Out Loud Machine Learning"
  repo-url: https://github.com/Waris-K/ML_blog
  repo-actions: [edit, issue]
format:
  html:
    theme: cosmo
    css: styles.css



