---
title: "Machine Learning : Learning Out Load"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: true
---
As I embark on the intriguing field of machine learning, this blog series will serve as my learning journal, in which I will decode complicated topics in an easy and relevant manner. In these few blogs, we'll look at the science underpinning anomaly detection and clustering with DBSCAN. Consider searching through data to find anomalies or group related entities - this is precisely what DBSCAN enables us to do. It acts as a data detective, revealing patterns and relationships that might otherwise go undiscovered.

As we go along, we'll unpack the importance of probability and random variables in machine learning. These aren't simply abstract mathematical concepts; they're the instruments we employ to deal with the uncertainty inherent in real-world facts. Moving forward, we'll look into regression, both linear and nonlinear, to see how we can anticipate outcomes and identify relationships within datasets. Finally, we'll conclude our adventure with a deep dive into classification, where we'll learn the ins and outs of labelling data points. So gear up for a learning experience as we work together to translate theoretical concepts into practical insights.

